{{- if and .Values.cleanup.deleteCRs .Values.global.privilegedRights -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "vm.cleanup.rbac.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "vm.cleanup.rbac.fullname" . }}
    app.kubernetes.io/component: victoriametrics
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/instance: {{ include "vm.cleanup.rbac.fullname" . }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
spec:
  template:
    metadata:
      name: {{ include "vm.cleanup.rbac.fullname" . }}
      labels:
        app.kubernetes.io/name: {{ include "vm.cleanup.rbac.fullname" . }}
        app.kubernetes.io/component: victoriametrics
        app.kubernetes.io/part-of: monitoring
        app.kubernetes.io/instance: {{ include "vm.cleanup.rbac.fullname" . }}
        app.kubernetes.io/version: {{ .Chart.AppVersion }}
    spec:
      serviceAccountName: {{ include "vm.cleanup.rbac.fullname" . }}
      restartPolicy: OnFailure
      {{- with .Values.cleanup.hook.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.cleanup.hook.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.cleanup.hook.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{ include "vm.cleanup.securityContext" . }}
      containers:
        - name: kubectl
          image: {{ include "vm.cleanup.image" . }}
          imagePullPolicy: IfNotPresent
          {{- with .Values.cleanup.hook.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.cleanup.hook.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          command:
            - /bin/sh
            - -c
            - >
              kubectl scale deployment --replicas=0 --selector app.kubernetes.io/component=monitoring-operator;
              sleep {{ .Values.cleanup.hook.timeout | default "10" }};
              kubectl delete vmusers --all --ignore-not-found=true;
              kubectl delete vmauths --all --ignore-not-found=true;
              kubectl delete vmalerts --all --ignore-not-found=true;
              kubectl delete vmagents --all --ignore-not-found=true;
              kubectl delete vmsingles --all --ignore-not-found=true;
              kubectl delete vmalertmanagers --all --ignore-not-found=true;
              kubectl delete vmclusters --all --ignore-not-found=true;
              sleep {{ .Values.cleanup.hook.timeout | default "10s" }};
{{- end -}}
