# Default values for grafana.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Deploy an Grafana instance
# Type: objects
# Mandatory: no

# Allow to enable deploy grafana
# Type: boolean
# Mandatory: no
# Default: true
#
install: true

# A docker image to use for prometheus-operator deployment with prometheus pod
#
# image: grafana/grafana:11.6.5

# Number of created pods.
# Type: integer
# Mandatory: no
# Default: 1
#
replicas: 1

# Set paused to reconciliation for grafana
# Type: boolean
# Mandatory: no
#
paused: false

# Pod monitor for self-monitoring
# Type: object
# Mandatory: no
#
podMonitor:
  install: true
  interval: 30s
  # Please note that scrapeTimeout must be less the interval
  scrapeTimeout: 10s
  metricRelabelings: []
    # - action: keep
    #   regex: 'kube_(daemonset|deployment|pod|namespace|node|statefulset).+'
    #   sourceLabels: [__name__]
  relabelings: []
    # - sourceLabels: [__meta_kubernetes_pod_node_name]
    #   separator: ;
    #   regex: ^(.*)$
    #   targetLabel: nodename
    #   replacement: $1
    #   action: replace

# Allows create Ingress for Grafana UI via monitoring-operator
# Type: object
# Mandatory: no
# Default: {}
#
ingress: {}
  # Indicates is Ingress need to be installed.
  # Marked as true if host specified.
  # Mandatory: no
  # Default: false
  #
  # install: false

  # FQDN of ingress host
  # Type: string
  # Mandatory: yes
  # Default: ""
  #
  # host: ""

  # Set of annotations for Ingress
  # Allows to set up authorization e.g. via ingress-nginx
  # Type: map[string]string
  # Mandatory: no
  # Default: {}
  #
  # annotations: {}

  # Set of labels for Ingress
  # Default monitoring-operator labels can be overwritten
  # Type: map[string]string
  # Mandatory: no
  # Default: {}
  #
  # labels: {}

  # Name of secret with TLS configs: tls.crt and tls.key
  # The secret must exist
  # Type: string
  # Mandatory: no
  # Default: ""
  #
# tlsSecretName: ""

# Allows set configuration for grafana. The properties used to generate grafana.ini.
# Ref: https://grafana.com/docs/grafana/latest/administration/configuration/
# Type: object
# Mandatory: no
#
config:
  auth:
    disable_login_form: false
    disable_signout_menu: true
  auth.anonymous:
    enabled: false
  analytics:
    reporting_enabled: false
    check_for_updates: false
  live:
    max_connections: 0
  log:
    level: warn
    mode: console

security:
  admin_user: admin
  admin_password: admin


# Provides a means to configure the grafana data storage
# Type: object
# Mandatory: no
#
# dataStorage:
#   labels:                 # Additional labels for the PVC
#     app: grafana
#   annotations:            # Additional annotations for the PVC
#     app: grafana
#   accessModes:            # An array of access modes, e.g. `ReadWriteOnce`
#     - ReadWriteOnce
#   size: 2Gi               # Requested size, e.g. `10Gi`
#   class: local-storage    # Storage class name

# Allows set extra system environment variables for grafana. The properties used to override values from grafana.ini.
# Ref: https://grafana.com/docs/grafana/latest/administration/configuration/#configure-with-environment-variables
# Type: object
# Mandatory: no
#
extraVars:
  GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: /etc/grafana-configmaps/grafana-home-dashboard/grafana-home-dashboard.json
  GF_LIVE_ALLOWED_ORIGINS: "*"
  GF_ANALYTICS_CHECK_FOR_PLUGIN_UPDATES: false
  GF_SECURITY_ANGULAR_SUPPORT_ENABLED: true
  GF_SECURITY_CONTENT_SECURITY_POLICY: true
  GF_SECURITY_COOKIE_SECURE: true
  GF_SECURITY_COOKIE_SAMESITE: "strict"
  GF_AUTH_LOGIN_COOKIE_NAME: "__Host-grafana_session"
  GF_AUTH_ANONYMOUS_HIDE_VERSION: true
  GF_SERVER_ENFORCE_DOMAIN: false
  # GF_RENDERING_SERVER_URL: http://grafana-image-renderer:8081/render
  # GF_RENDERING_CALLBACK_URL: http://grafana-service:3000/
  # GF_AUTH_GENERIC_OAUTH_TLS_SKIP_VERIFY_INSECURE: true
  # GF_LOG_LEVEL: trace
  # GF_SECURITY_CONTENT_SECURITY_POLICY_TEMPLATE:

# Allows set extra system environment variables for Grafana like an extraVars,
# but set variables into the Secret instead of ConfigMap.
# If extraVars and ExtraVarsSecret have variables with equals keys, value will be taken from the Secret.
# Type: object
# Mandatory: no
# Default: {}
#
extraVarsSecret: {}
# GF_AUTH_GENERIC_OAUTH_CLIENT_ID and GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET will be populated from OAuth2 proxy secret.

## Allows set custom home dashboard for grafana.
## GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: /etc/grafana-configmaps/grafana-home-dashboard/grafana-home-dashboard.json
# Type: object
# Mandatory: no
# Default: true
#
grafanaHomeDashboard: true

## Enables Backup Daemon Dashboard installation.
# Type: object
# Mandatory: no
# Default: true
#
backupDaemonDashboard: true

## dashboardLabelSelector allows to query over a set of resources according to labels.
## The result of matchLabels and matchExpressions are ANDed.
## An empty label selector matches all objects. A null label selector matches no objects.
## The parameter is an array of labelSelector objects
## https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.29/#labelselector-v1-meta
# Type: []object
#
dashboardLabelSelector: [{}]

## dashboardNamespaceSelector allows to query over a set of resources in namespaces that fits label selector.
## The result of matchLabels and matchExpressions are ANDed.
## An empty label selector matches all objects. A null label selector matches no objects.
## The parameter is labelSelector object type
## https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.29/#labelselector-v1-meta
# Type: object
#
dashboardNamespaceSelector:
  matchExpressions:
    - key: openshift.io/cluster-monitoring
      operator: NotIn
      values: [ "true" ]

# The resources describes the compute resource requests and limits for single Pods.
# Ref: https://kubernetes.io/docs/user-guide/compute-resources/
# Type: object
# Mandatory: no
#
resources: {}
#  limits:
#    cpu: 500m
#    memory: 800Mi
#  requests:
#    cpu: 300m
#    memory: 400Mi

# SecurityContext holds pod-level security attributes.
# The parameters are required if a Pod Security Policy is enabled
# for Kubernetes cluster and required if a Security Context Constraints is enabled
# for Openshift cluster.
# Type: object
# Mandatory: no
#
securityContext: {}
  # The UID to run the entrypoint of the container process.
  # Defaults to user specified in image metadata if unspecified.
  # Type: integer
  # Mandatory: no
  #
  # runAsUser: 2000

  # A special supplemental group that applies to all containers in a pod.
  # Some volume types allow the Kubelet to change the ownership of that volume
  # to be owned by the pod:
  #   1. The owning GID will be the FSGroup
  #   2. The setgid bit is set (new files created in the volume will be owned by FSGroup)
  #   3. The permission bits are OR'd with rw-rw----
  # If unset, the Kubelet will not modify the ownership and permissions of any volume.
  # Type: integer
  # Mandatory: no
  #
  # fsGroup: 2000

# Tolerations allow the pods to schedule onto nodes with matching taints.
# Type: object
# Mandatory: no
#
tolerations: []

# Allow define which Nodes the Pods are scheduled on.
# Type: map[string]
# Mandatory: no
# Default: not set
#
nodeSelector: {}

# If specified, the pod's scheduling constraints
# More info: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.30/#affinity-v1-core
# Type: object
# Mandatory: no
# Default: not set
#
affinity: {}

# Annotations is an unstructured key value map stored
# with a resource that may be set by external tools to store and retrieve arbitrary metadata.
# They are not queryable and should be preserved when modifying objects.
# More info: https://kubernetes.io/docs/user-guide/annotations
# Type: map[string]string
# Mandatory: no
# Default: not set
#
annotations: {}
#  annotation-key: annotation-value

# Map of string keys and values that can be used to organize and categorize (scope and select) objects.
# May match selectors of replication controllers and services.
# More info: https://kubernetes.io/docs/user-guide/labels
# Type: map[string]string
# Mandatory: no
# Default: not set
#
labels: {}
#  label-key: label-value

# PriorityClassName assigned to the Pods to prevent grafana pods from evicting.
# Type: string
# priorityClassName: "priorityClassName"

# Service account for monitoring-operator to use.
# Ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/
serviceAccount:

  # Annotations is an unstructured key value map stored
  # with a resource that may be set by external tools to store and retrieve arbitrary metadata.
  # They are not queryable and should be preserved when modifying objects.
  # More info: https://kubernetes.io/docs/user-guide/annotations
  # Type: map[string]string
  # Mandatory: no
  # Default: not set
  #
  annotations: {}
  # eks.amazonaws.com/role-arn: <IAM_PROXY_PROMETHEUS_ROLE_ARN>

  # Map of string keys and values that can be used to organize and categorize (scope and select) objects.
  # May match selectors of replication controllers and services.
  # More info: https://kubernetes.io/docs/user-guide/labels
  # Type: map[string]string
  # Mandatory: no
  # Default: not set
  #
  labels: {}
  # app.kubernetes.io/managed-by: helm

# PriorityClassName assigned to the Pods to prevent them from evicting.
# Type: string
# priorityClassName: "priorityClassName"

# Manages Grafana component
# Type: object
# Mandatory: yes
#
operator:

  # A docker image to use for prometheus-operator deployment with prometheus pod
  # Type: string
  # Mandatory: yes
  #
  # image: grafana-operator/grafana-operator:v4.1.1

  # Set paused to reconciliation for grafana-operator
  # Type: boolean
  # Mandatory: no
  #
  paused: false

  ## Comma separated list of namespaces to monitor in non-privileged mode.
  # This parameter is unnecessary if the grafana-operator has ClusterRole on all namespaces.
  # Type string
  # Mandatory: no
  #
  # namespaces: ""

  # A docker image to use for grafana-plugins-init container
  # Type: string
  # Mandatory: yes
  #
  # initContainerImage: product/prod.platform.system.monitoring_grafana-plugins-init:latest

  # The resources describes the compute resource requests and limits for single Pods.
  # Ref: https://kubernetes.io/docs/user-guide/compute-resources/
  # Type: object
  # Mandatory: no
  #
  resources: {}
  #  limits:
  #    cpu: 100m
  #    memory: 100Mi
  #  requests:
  #    cpu: 50m
  #    memory: 50Mi

  # PriorityClassName assigned to the Pods to prevent grafana-operator pods from evicting.
  # Type: string
  # priorityClassName: "priorityClassName"

  podMonitor:
    install: true
    interval: 30s
    # Please note that scrapeTimeout must be less the interval
    scrapeTimeout: 10s
    metricRelabelings:
      - action: drop
        regex: controller_runtime_reconcile_time_seconds_bucket;(0.005|0.01|0.025|0.05|0.15|0.2|0.25|0.3|0.35|0.4|0.45|0.6|0.7|0.8|0.9|1.25|1.5|1.75|2.5|3|3.5|4|4.5|6|7|8|9|15|20|25|40|50)
        sourceLabels: ['__name__','le']
      # - action: keep
      #   regex: 'kube_(daemonset|deployment|pod|namespace|node|statefulset).+'
      #   sourceLabels: [__name__]
    relabelings: []
      # - sourceLabels: [__meta_kubernetes_pod_node_name]
      #   separator: ;
      #   regex: ^(.*)$
      #   targetLabel: nodename
      #   replacement: $1
      #   action: replace

  ## SecurityContext holds pod-level security attributes.
  ## The parameters are required if a Pod Security Policy is enabled
  ## for Kubernetes cluster and required if a Security Context Constraints is enabled
  ## for Openshift cluster.
  # Type: object
  # Mandatory: no
  #
  securityContext: {}
    # The UID to run the entrypoint of the container process.
    # Defaults to user specified in image metadata if unspecified.
    # Type: integer
    # Mandatory: no
    #
    # runAsUser: 2000

    # A special supplemental group that applies to all containers in a pod.
    # Some volume types allow the Kubelet to change the ownership of that volume
    # to be owned by the pod:
    #   1. The owning GID will be the FSGroup
    #   2. The setgid bit is set (new files created in the volume will be owned by FSGroup)
    #   3. The permission bits are OR'd with rw-rw----
    # If unset, the Kubelet will not modify the ownership and permissions of any volume.
    # Type: integer
    # Mandatory: no
    #
  # fsGroup: 2000

  # Tolerations allow the pods to schedule onto nodes with matching taints.
  # Type: object
  # Mandatory: no
  #
  tolerations: []

  # Allow define which Nodes the Pods are scheduled on.
  # Type: map[string]
  # Mandatory: no
  # Default: not set
  #
  nodeSelector: {}

  # If specified, the pod's scheduling constraints
  # More info: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.30/#affinity-v1-core
  # Type: object
  # Mandatory: no
  # Default: not set
  #
  affinity: {}
  
  # Annotations is an unstructured key value map stored
  # with a resource that may be set by external tools to store and retrieve arbitrary metadata.
  # They are not queryable and should be preserved when modifying objects.
  # More info: https://kubernetes.io/docs/user-guide/annotations
  # Type: map[string]string
  # Mandatory: no
  # Default: not set
  #
  annotations: {}
  #  annotation-key: annotation-value

  # Map of string keys and values that can be used to organize and categorize (scope and select) objects.
  # May match selectors of replication controllers and services.
  # More info: https://kubernetes.io/docs/user-guide/labels
  # Type: map[string]string
  # Mandatory: no
  # Default: not set
  #
  labels: {}
  #  label-key: label-value

  # Allow specification of log level
  # Type: string
  # Mandatory: no
  # Default: not set
  logLevel: info

  # Service account for monitoring-operator to use.
  # Ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/
  serviceAccount:

    # Annotations is an unstructured key value map stored
    # with a resource that may be set by external tools to store and retrieve arbitrary metadata.
    # They are not queryable and should be preserved when modifying objects.
    # More info: https://kubernetes.io/docs/user-guide/annotations
    # Type: map[string]string
    # Mandatory: no
    # Default: not set
    #
    annotations: {}
    # eks.amazonaws.com/role-arn: <IAM_PROXY_PROMETHEUS_ROLE_ARN>

    # Map of string keys and values that can be used to organize and categorize (scope and select) objects.
    # May match selectors of replication controllers and services.
    # More info: https://kubernetes.io/docs/user-guide/labels
    # Type: map[string]string
    # Mandatory: no
    # Default: not set
    #
    labels: {}
    # app.kubernetes.io/managed-by: helm

  # PriorityClassName assigned to the Pods to prevent them from evicting.
  # Type: string
  # priorityClassName: "priorityClassName"

# Allows rendering panels and dashboards to PNGs using a headless browser
# Type: object
# Mandatory: no
#
imageRenderer:
  # Allow to enable deploy grafana image renderer
  # Type: boolean
  # Mandatory: no
  # Default: false
  #
  install: false

  # A name of the microservice to deploy with.
  # This name is used as the name of the microservice deployment and in labels.
  # Type: string
  # Mandatory: no
  # Default: grafana-image-renderer
  #
  name: grafana-image-renderer

  # A docker image to use for grafana-image-renderer deployment
  #
  # image: grafana/grafana-image-renderer:3.12.9

  securityContext: {}
    # The UID to run the entrypoint of the container process.
    # Defaults to user specified in image metadata if unspecified.
    # Type: integer
    # Mandatory: no
    #
    # runAsUser: 2000

    # A special supplemental group that applies to all containers in a pod.
    # Some volume types allow the Kubelet to change the ownership of that volume
    # to be owned by the pod:
    #   1. The owning GID will be the FSGroup
    #   2. The setgid bit is set (new files created in the volume will be owned by FSGroup)
    #   3. The permission bits are OR'd with rw-rw----
    # If unset, the Kubelet will not modify the ownership and permissions of any volume.
    # Type: integer
    # Mandatory: no
    #
    # fsGroup: 2000

  # Tolerations allow the pods to schedule onto nodes with matching taints.
  # Type: object
  # Mandatory: no
  #
  tolerations: []

  # Allow define which Nodes the Pods are scheduled on.
  # Type: map[string]
  # Mandatory: no
  # Default: not set
  #
  nodeSelector: {}
  
  # If specified, the pod's scheduling constraints
  # More info: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.30/#affinity-v1-core
  # Type: object
  # Mandatory: no
  # Default: not set
  #
  affinity: {}

  # Annotations is an unstructured key value map stored
  # with a resource that may be set by external tools to store and retrieve arbitrary metadata.
  # They are not queryable and should be preserved when modifying objects.
  # More info: https://kubernetes.io/docs/user-guide/annotations
  # Type: map[string]string
  # Mandatory: no
  # Default: not set
  #
  annotations: {}
  #  annotation-key: annotation-value

  # Map of string keys and values that can be used to organize and categorize (scope and select) objects.
  # May match selectors of replication controllers and services.
  # More info: https://kubernetes.io/docs/user-guide/labels
  # Type: map[string]string
  # Mandatory: no
  # Default: not set
  #
  labels: {}
  #  label-key: label-value

  # Port for grafana-image-renderer service.
  # Type: integer
  # Mandatory: no
  # Default: 8282
  #
  port: 8282

  # The resources describes the compute resource requests and limits for single Pods.
  # Ref: https://kubernetes.io/docs/user-guide/compute-resources/
  # Type: object
  # Mandatory: no
  #
  resources: {}
  #  limits:
  #    cpu: 300m
  #    memory: 500Mi
  #  requests:
  #    cpu: 150m
  #    memory: 250Mi

  # extra environment variables
  extraEnvs:
    LOG_LEVEL: info
    RENDERING_ARGS: --no-sandbox,--disable-setuid-sandbox,--disable-dev-shm-usage,--disable-accelerated-2d-canvas,--disable-gpu,--window-size=1280x758
    IGNORE_HTTPS_ERRORS: true
    # RENDERING_MODE: clustered
    # IGNORE_HTTPS_ERRORS: true
    # RENDERING_MODE=clustered
    # RENDERING_CLUSTERING_MODE=browser
    # RENDERING_CLUSTERING_MAX_CONCURRENCY=5
    # RENDERING_CLUSTERING_TIMEOUT=30
    # RENDERING_VERBOSE_LOGGING=true
    # RENDERING_DUMPIO=true

  # PriorityClassName assigned to the Pods to prevent them from evicting.
  # Type: string
  # priorityClassName: "priorityClassName"
