{{- if eq .Values.publicCloudName "" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.etcdCertsJob.rbac.clusterRoleBindingName }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.etcdCertsJob.rbac.serviceAccountName }}
    namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.etcdCertsJob.rbac.clusterRoleName }}
{{- end }}
