{{- if and ( .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" ) .Values.kubernetesMonitors.kubeControllerManagerServiceMonitor.install (empty .Values.publicCloudName) }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ printf "%s-%s" .Release.Namespace "kube-controller-manager-service-monitor" | nospace | trunc 63 | trimSuffix "-" }}
  labels:
    app.kubernetes.io/name: {{ printf "%s-%s" .Release.Namespace "kube-controller-manager-service-monitor" | nospace | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/component: service-monitor
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/instance: {{ printf "%s-%s" .Release.Namespace "kube-controller-manager-service-monitor" | nospace | trunc 63 | trimSuffix "-" }}
    {{- if .Values.kubernetesMonitors.kubeControllerManagerServiceMonitor.labels }}
    {{- toYaml .Values.kubernetesMonitors.kubeControllerManagerServiceMonitor.labels | nindent 4 }}
    {{- end }}
spec:
  endpoints:
  - interval: {{ .Values.kubernetesMonitors.kubeControllerManagerServiceMonitor.interval }}
    scrapeTimeout: {{ .Values.kubernetesMonitors.kubeControllerManagerServiceMonitor.scrapeTimeout }}
    scheme: https
    port: https-metrics
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    {{- if .Values.kubernetesMonitors.kubeControllerManagerServiceMonitor.relabelings }}
    relabelings:
    {{- toYaml .Values.kubernetesMonitors.kubeControllerManagerServiceMonitor.relabelings | nindent 6 }}
    {{- end }}
    {{- if .Values.kubernetesMonitors.kubeControllerManagerServiceMonitor.metricRelabelings }}
    metricRelabelings:
    {{- toYaml .Values.kubernetesMonitors.kubeControllerManagerServiceMonitor.metricRelabelings | nindent 6 }}
    {{- end }}
    tlsConfig:
      insecureSkipVerify: true
  jobLabel: {{ .Values.kubernetesMonitors.kubeControllerManagerServiceMonitor.jobLabel | default "k8s-app" }}
  namespaceSelector:
    matchNames:
    {{- if .Values.kubernetesMonitors.kubeControllerManagerServiceMonitor.namespaceSelector }}
    {{- toYaml .Values.kubernetesMonitors.kubeControllerManagerServiceMonitor.namespaceSelector.matchNames | nindent 6 }}
    {{- else }}
      - {{ .Release.Namespace }}
    {{- end }}
  selector:
    matchLabels:
    {{- if .Values.kubernetesMonitors.kubeControllerManagerServiceMonitor.selector }}
    {{- toYaml .Values.kubernetesMonitors.kubeControllerManagerServiceMonitor.selector | nindent 6 }}
    {{- else }}
      k8s-app: kube-controller-manager
    {{- end }}
{{- end }}
