# Default values for network-latency-exporter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Allow to disable deploy network-latency-exporter.
# Type: boolean
# Mandatory: no
# Default: false
#
install: false

# Provide a name in place of network-latency-exporter for labels.
# Type: string
# Mandatory: no
# Default: "network-latency-exporter"
#
name: "network-latency-exporter"

rbac:
  # Allow creating ClusterRole. If set to `false`, ClusterRole must be created manually.
  # Type: boolean
  # Mandatory: no
  # Default: true
  #
  createClusterRole: true

  # Allow creating ClusterRoleBinding. If set to `false`, ClusterRoleBinding must be created manually.
  # Type: boolean
  # Mandatory: no
  # Default: true
  #
  createClusterRoleBinding: true

  # Allow creating PodSecurityPolicy or SecurityContextConstraints.
  # If set to `false`, PodSecurityPolicy / SecurityContextConstraints must be created manually.
  # Type: boolean
  # Mandatory: no
  # Default: true
  #
  setupSecurityContext: true

  # If `true`, set parameters in PSP or SCC for ability to running container in the privileged mode and set
  # `privileged: true` to the security context in the exporter's container.
  # Type: boolean
  # Mandatory: no
  # Default: false
  #
  privileged: false

# Allow creating Grafana Dashboards for network-latency-exporter.
# Type: boolean
# Mandatory: no
# Default: true
#
createGrafanaDashboards: true

# Service account for network-latency-exporter to use.
# Ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/
# Type: object
#
serviceAccount:

  # Allow creating ServiceAccount.
  # If set to `false`, ServiceAccount must be created manually.
  # Type: boolean
  # Mandatory: no
  # Default: true
  #
  create: true

  # Provide a name in place of network-latency-exporter for ServiceAccount.
  # Type: string
  # Mandatory: no
  # Default: "network-latency-exporter"
  #
  name: "network-latency-exporter"

# A docker image to use for network-latency-exporter daemonset.
# Type: string
# Mandatory: yes
#
# image: ghcr.io/netcracker/qubership-network-latency-exporter:latest

# The resources describes the compute resource requests and limits for single Pods.
# Ref: https://kubernetes.io/docs/user-guide/compute-resources/
# Type: object
# Mandatory: no
#
resources: {}
#  limits:
#    cpu: 200m
#    memory: 256Mi
#  requests:
#    cpu: 100m
#    memory: 128Mi

# SecurityContext holds pod-level security attributes.
# The parameters are required if a Pod Security Policy is enabled
# for Kubernetes cluster and required if a Security Context Constraints is enabled
# for OpenShift cluster.
# Type: object
# Mandatory: no
#
securityContext: {}
  # The UID to run the entrypoint of the container process.
  # Defaults to user specified in image metadata if unspecified.
  # The default value is set to "0",
  # because otherwise the exporter does not work correctly.
  # Type: integer
  # Mandatory: no
  #
  # runAsUser: "0"

  # A special supplemental group that applies to all containers in a pod.
  # Some volume types allow the Kubelet to change the ownership of that volume
  # to be owned by the pod:
  #   1. The owning GID will be the FSGroup
  #   2. The setgid bit is set (new files created in the volume will be owned by FSGroup)
  #   3. The permission bits are OR'd with rw-rw----
  # If unset, the Kubelet will not modify the ownership and permissions of any volume.
  # Type: integer
  # Mandatory: no
  #
  # fsGroup: 2000

# Tolerations allow the pods to schedule onto nodes with matching taints.
# Default tolerations "operator: Exists" for installing on master nodes
# Type: object
# Mandatory: no
#
tolerations:
  - operator: Exists

# Allow to define which Nodes the Pods are scheduled on.
# Type: map[string]
# Mandatory: no
# Default: not set
#
nodeSelector: {}

# If specified, the pod's scheduling constraints
# More info: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.30/#affinity-v1-core
# Type: object
# Mandatory: no
# Default: not set
#
affinity: {}

extraArgs: []
 #  - "--web.listen-address=:9100"
 #  - "--web.telemetry-path=/metrics"
 #  - "--web.max-requests=40"

# Allow enabling/disabling script for discovering nodes IP.
# Type: boolean
# Mandatory: no
# Default: true
#
discoverEnable: true



# The response time for each packet sent which the application waits response, in seconds.
# Type: integer
# Mandatory: no
# Default: 3
#
requestTimeout: 3

# The metrics collection timeout. Can be calculated as
# TIMEOUT = 10s + (REQUEST_TIMEOUT * PACKETS_NUM * <NUMBER_OF_PROTOCOLS>)
# Type: string
# Mandatory: no
# Default: 100s
#
timeout: 100s

# The number of packets to send per probe.
# Type: integer
# Mandatory: no
# Default: 10
#
packetsNum: 10

# The size of packet to sent in bytes.
# Type: integer
# Mandatory: no
# Default: 64
#
packetSize: 64

# The comma-separated list of network protocols and ports (separated by ':') via which packets will be sent.
# Supported protocols: `UDP`, `TCP`, `ICMP`. If no port specified for protocol, port `1` will be used.
# Type: string
# Mandatory: no
# Default: "UDP:80,TCP:80,ICMP"
#
checkTarget: "UDP:80,TCP:80,ICMP"

# The comma-separated list of collectors.
# Supported latency types: `node_collector`.
# Type: string
# Mandatory: no
# Default: "node_collector"
#
latencyTypes: "node_collector"

serviceMonitor:
  # If true, a ServiceMonitor is created for a `prometheus-operator`.
  # Type: boolean
  # Mandatory: no
  # Default: true
  #
  enabled: true

  # Scraping interval for Prometheus.
  # Type: string
  # Mandatory: no
  # Default: 30s
  #
  interval: 30s

  # Scraping timeout for Prometheus.
  # Type: string
  # Mandatory: no
  # Default: 20s
  #
  scrapeTimeout: 20s

# Allows specifying custom labels for DaemonSet of `network-latency-exporter`.
# Type: object
# Mandatory: no
# Default: not set
#
# additionalLabels:
#   key: value

# Annotations is an unstructured key value map stored
# with a resource that may be set by external tools to store and retrieve arbitrary metadata.
# They are not queryable and should be preserved when modifying objects.
# More info: https://kubernetes.io/docs/user-guide/annotations
# Type: map[string]string
# Mandatory: no
# Default: not set
#
annotations: {}
#  annotation-key: annotation-value

# Map of string keys and values that can be used to organize and categorize (scope and select) objects.
# May match selectors of replication controllers and services.
# More info: https://kubernetes.io/docs/user-guide/labels
# Type: map[string]string
# Mandatory: no
# Default: not set
#
labels: {}
#  label-key: label-value

# PriorityClassName assigned to the Pods to prevent them from evicting.
# Type: string
# priorityClassName: "priorityClassName"
