---
name: Check Go Modules Licenses
on:
  push:

jobs:
  check-license:
    uses: Netcracker/qubership-workflow-hub/.github/workflows/go-check-license.yaml@3e428f45132119ce49d90f3770a45d4fe1d1078d # v2.0.4
